name: Automatic pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review_pull_request:
    name: Pull request review by Danger
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # actions/cache@v5.0.5
      id: bundlerCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup CI environment
      uses: ./.github/actions/setup-ci-environment
      with:
        bundler-cache: "false"
        bundle-install-command: "bundle install --path vendor/bundle"

    - name: Setup ENV file
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        touch .env
        echo $ENV | base64 --decode > .env

    - name: Run Arkana
      run: bundle exec arkana

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput

    - name: Review pull request by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
