name: Deploy Production Build To Firebase

on:
  push:
    branches: [ release/** ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 1
    - uses: ./.github/actions/swiftlint

  deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
        with:
          fetch-depth: 1
          
      - name: Build and Deploy to Firebase
        uses: ./.github/actions/build-and-deploy-firebase
        with:
          environment: Production
          build_and_test_lane: buildAndTest
          code_signing_lane: syncAdHocProductionCodeSigning
          build_and_upload_lane: buildProductionAndUploadToFirebase
          tag_type: Production_Firebase
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          match_password: ${{ secrets.MATCH_PASSWORD }}
          firebase_credentials_base64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
          env_file: ${{ secrets.ENV_FILE }}

