# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def main_pods
  pod 'Alamofire'
end

target '{project-name}' do
  main_pods
end

target '{project-name} staging' do

  main_pods

  target '{project-name}Tests' do
    # Pods for testing
  end

  target '{project-name}UITests' do
    # Pods for testing
  end

end
