# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def main_pods
  pod 'Alamofire'
end

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target '{project-name}' do
  main_pods
end

target '{project-name} staging' do
  main_pods
end

target '{project-name}Tests' do
  testing_pods
end

target '{project-name}UITests' do
  testing_pods
end
