version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.cicdtemplate/.github/workflows"
      - "/.cicdtemplate/.github/self-hosted-workflows"
      - "/.github/actions/setup-ci-environment"
      - "/.github/actions/swiftlint"
      - "/.cicdtemplate/.github/actions/build-and-deploy-firebase"
      - "/.cicdtemplate/.github/actions/setup-ci-environment"
      - "/.cicdtemplate/.github/actions/swiftlint"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        applies-to: version-updates
        group-by: dependency-name
