sources:
  - TemplateApp/Sources
templates:
  - tools/sourcery/templates
output:
  TemplateAppTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - TemplateApp
  autoMockableImports:
    - RxSwift
    - RxCocoa
