sources:
  - SurveyTests/Sources
templates:
  - tools/sourcery/templates
output:
  SurveyTestsTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - SurveyTests
  autoMockableImports:
    - RxSwift
    - RxCocoa
