sources:
  - TestDanger/Sources
templates:
  - tools/sourcery/templates
output:
  TestDangerTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - TestDanger
  autoMockableImports:
    - RxSwift
    - RxCocoa
