sources:
  - AddDanger/Sources
templates:
  - tools/sourcery/templates
output:
  AddDangerTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - AddDanger
  autoMockableImports:
    - RxSwift
    - RxCocoa
