parent_config: tools/SwiftLint/base.yml

included:
  - {PROJECT_NAME}
  - {PROJECT_NAME}Tests
  - {PROJECT_NAME}UITests

excluded:
  - {PROJECT_NAME}Tests/Sources/Mocks/Sourcery/AutoMockable.generated.swift
  - {PROJECT_NAME}/Sources/Supports/Helpers/Rswift/R.generated.swift
  - Pods
  - Derived
  - DerivedData
