child_config: tools/SwiftLint/.base.yml
parent_config: tools/SwiftLint/.custom_rules.yml

included:
  - {PROJECT_NAME}
  - {PROJECT_NAME}Tests
  - {PROJECT_NAME}UITests

excluded:
  - {PROJECT_NAME}Tests/Sources/Mocks/Sourcery/AutoMockable.generated.swift
  - **/*/*.generated.swift
  - Pods
  - Derived
  - DerivedData
