name: Automatic pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prebuild_review:
    name: Prebuild PR review by Danger
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # actions/checkout@v7.0.0
      with:
        fetch-depth: 0

    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # actions/cache@v6.1.0
      id: bundlerCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup CI environment
      uses: ./.github/actions/setup-ci-environment
      with:
        bundler-cache: "false"
        bundle-install-command: "bundle config set --local path 'vendor/bundle' && bundle install"

    - name: Prebuild PR review by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger --dangerfile=template/PrebuildDangerfile

  build_and_test:
    name: Build and Test
    runs-on: [self-hosted, macOS]
    needs: prebuild_review
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # actions/checkout@v7.0.0
      with:
        fetch-depth: 0

    - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # actions/cache@v6.1.0
      id: bundlerCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup CI environment
      uses: ./.github/actions/setup-ci-environment
      with:
        bundler-cache: "false"
        bundle-install-command: "bundle config set --local path 'vendor/bundle' && bundle install"

    - name: Setup ENV file
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        touch .env
        echo $ENV | base64 --decode > .env

    - name: Bundle install
      run: bundle config set --local path 'vendor/bundle' && bundle install

    - name: Run Arkana
      run: bundle exec arkana

    - name: Modify test plan
      run: |
        mise exec -- xcode-selective-test {PROJECT_NAME}.xcodeproj \
        --test-plan {PROJECT_NAME}.xctestplan \
        --base-branch origin/${{ github.base_ref }}

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput

    - name: Post-build PR review by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
