name: Automatic pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review_pull_request:
    name: Pull request review by Danger
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # actions/cache@v4.3.0
      id: bunlderCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install tools with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # jdx/mise-action@v4.0.1

    - name: Setup ENV file
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        touch .env
        echo $ENV | base64 --decode > .env

    - name: Bundle install
      run: bundle install --path vendor/bundle
      
    - name: Run Arkana
      run: bundle exec arkana

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput

    - name: Review pull request by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
