name: Automatic pull request review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  early_review:
    name: Early PR review by Danger
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # actions/cache@v5.0.4
      id: bundlerCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup CI environment
      uses: ./.github/actions/setup-ci-environment
      with:
        bundler-cache: "false"
        bundle-install-command: "bundle config set --local path 'vendor/bundle' && bundle install"

    - name: Early PR review by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger --dangerfile=template/EarlyDangerfile

  build_and_test:
    name: Build and Test
    runs-on: [self-hosted, macOS]
    needs: early_review
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 0

    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # actions/cache@v5.0.4
      id: bundlerCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup CI environment
      uses: ./.github/actions/setup-ci-environment
      with:
        bundler-cache: "false"
        bundle-install-command: "bundle config set --local path 'vendor/bundle' && bundle install"

    - name: Setup ENV file
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        touch .env
        echo $ENV | base64 --decode > .env

    - name: Bundle install
      run: bundle config set --local path 'vendor/bundle' && bundle install

    - name: Run Arkana
      run: bundle exec arkana

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput

    - name: Post-build PR review by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
