name: Deploy Staging Build To Firebase

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy_firebase.yml
    with:
      environment: Staging
      build_and_test_lane: buildAndTest
      code_signing_lane: syncAdHocStagingCodeSigning
      build_and_upload_lane: buildStagingAndUploadToFirebase
      tag_type: Staging_Firebase
      create_release_note: true
      install_firebase_tools: true
    secrets: inherit
