name: Deploy Production Build To Firebase

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### FIREBASE_GOOGLE_APPLICATION_CREDENTIALS_BASE64

on:
  push:
    branches: [ release/** ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
      with:
        fetch-depth: 0
    - uses: ./.github/actions/swiftlint

  build:
    name: Build
    runs-on: [self-hosted, macOS]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6.0.2
    # Set fetch-depth (default: 1) to get whole tree
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 # webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup ENV file
      env:
        ENV: ${{ secrets.ENV }}
      run: |
        touch .env
        echo $ENV | base64 --decode > .env

    - name: Read Google Service Account
      id: firebase_service_account
      uses: timheuer/base64-to-file@adaa40c0c581f276132199d4cf60afa07ce60eac # timheuer/base64-to-file@v1.2
      with:
        fileName: 'firebase_service_account.json'
        encodedString: ${{ secrets.FIREBASE_GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

    - name: Install tools with mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # jdx/mise-action@v4.0.1

    - name: Bundle install
      run: bundle install
      
    - name: Run Arkana
      run: bundle exec arkana

    - name: Build and Test
      run: bundle exec fastlane buildAndTest

    - name: Match Ad-hoc
      run: bundle exec fastlane syncAdHocProductionCodeSigning
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Build Production App and Distribute to Firebase
      run: bundle exec fastlane buildProductionAndUploadToFirebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.firebase_service_account.outputs.filePath }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # actions/upload-artifact@v4.6.2
      with:
        name: ${{ format('v{0}({1})-{2}', env.VERSION_NUMBER, env.BUILD_NUMBER, env.TAG_TYPE) }}
        path: |
          ${{ env.IPA_OUTPUT_PATH }}
          ${{ env.DSYM_OUTPUT_PATH }}
      env:
        TAG_TYPE: Production_Firebase

    - name: Remove keychain
      if: ${{ always() }}
      run: bundle exec fastlane removeKeychain
      continue-on-error: true
