# frozen_string_literal: true

require '././Constants/Environments'
require '././Constants/DeliverableConstants'

private_lane :template_app_icon do
  appicon(
    appicon_image_file: 'fastlane/Tests/appicon.png',
    appicon_devices: %i[iphone ios_marketing],
    appicon_path: '{PROJECT_NAME}/Resources/Assets/Assets.xcassets'
  )
end

private_lane :disable_exempt_encryption do
  set_info_plist_value(path: "{PROJECT_NAME}/Configurations/Plists/Info.plist", key: "ITSAppUsesNonExemptEncryption", value: false)
end

private_lane :increment_test_build_number do
  app_store_connect_api_key(
    key_id: DeliverableConstants.APP_STORE_KEY_ID,
    issuer_id: DeliverableConstants.APP_STORE_ISSUER_ID,
    key_path: "appstorekey.p8"
  )
  increment_build_number({
    build_number: latest_testflight_build_number + 1
  })
end

lane :set_up_test_project do
  template_app_icon
  disable_exempt_encryption
  increment_test_build_number
end