# frozen_string_literal: true

private_lane :template_app_icon do
  appicon(
    appicon_image_file: 'fastlane/Tests/appicon.png',
    appicon_devices: %i[iphone ios_marketing],
    appicon_path: '{PROJECT_NAME}/Resources/Assets/Assets.xcassets'
  )
end

private_lane :disable_exempt_encryption do
  set_info_plist_value(path: "{PROJECT_NAME}/Configurations/Plists/Info.plist", key: "ITSAppUsesNonExemptEncryption", value: false)
end

lane :set_up_test_project do
  template_app_icon
  disable_exempt_encryption
end

lane :update_provision_settings do
  update_project_provisioning(
    profile: ENV['sigh_{BUNDLE_ID_PRODUCTION}_appstore_profile-path']
  )
end