// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation

public protocol ArkanaKeysGlobalProtocol {
}

public protocol ArkanaKeysEnvironmentProtocol {
    var clientId: String { get }
    var clientSecret: String { get }
}
