// DO NOT MODIFY
// Automatically generated by Arkana (https://github.com/rogerluan/arkana)

import Foundation
import ArkanaKeysInterfaces

public enum ArkanaKeys {
    @inline(__always)
    fileprivate static let salt: [UInt8] = [
        0xd2, 0x75, 0x5, 0xb9, 0x43, 0x89, 0x1e, 0xf9, 0x75, 0x76, 0x62, 0x24, 0x4e, 0x5d, 0x29, 0x8b, 0x92, 0x8a, 0x2, 0x31, 0x99, 0xf4, 0xf1, 0x34, 0x16, 0x6c, 0x11, 0xc8, 0xea, 0xe8, 0xe6, 0xed, 0xa9, 0x37, 0xec, 0xd9, 0xd9, 0x81, 0x49, 0x3b, 0x89, 0x89, 0x13, 0xee, 0xef, 0xa8, 0xce, 0xc6, 0x30, 0xc4, 0xa, 0x58, 0xee, 0xa7, 0xee, 0x64, 0xaa, 0xa0, 0x60, 0x1c, 0x4d, 0x94, 0x84, 0xf9
    ]

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> String {
        return String(decoding: encoded.enumerated().map { offset, element in
            element ^ cipher[offset % cipher.count]
        }, as: UTF8.self)
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Bool {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Bool(stringValue)!
    }

    static func decode(encoded: [UInt8], cipher: [UInt8]) -> Int {
        let stringValue: String = Self.decode(encoded: encoded, cipher: cipher)
        return Int(stringValue)!
    }
}

public extension ArkanaKeys {
    struct Global: ArkanaKeysGlobalProtocol {
        public init() {}
    }
}

public extension ArkanaKeys {
    struct Staging: ArkanaKeysEnvironmentProtocol {
        public init() {}
    }
}

public extension ArkanaKeys {
    struct Release: ArkanaKeysEnvironmentProtocol {
        public init() {}
    }
}
