disabled_rules:
    - file_name
    - type_body_length
    - file_types_order
    - type_name
    - vertical_whitespace_types
    - line_length
    - type_contents_order
    - opening_brace
    - identifier_name
    - file_length
