platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def testing_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'Sourcery'
  pod 'OHHTTPStubs/Swift'
end

target '___PACKAGENAME___' do
  pod 'NimbleExtension', :git => 'https://github.com/nimblehq/NimbleExtension', :branch => 'master'

  pod 'SnapKit'
  pod 'Alamofire'
  pod 'R.swift'
  pod 'SwiftLint'
  
  pod 'Crashlytics'

  target 'UnitTests' do
    inherit! :search_paths
    testing_pods
  end

  target 'UITests' do
    testing_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
