require("dotenv")
Dotenv.load

import "./Crashlytics/Crashfile"
import "./iTunesConnect/Connectfile"
import "./Developer Portal/Codefile"

default_platform(:ios)

platform :ios do
  private_lane :bump_build do
    build_number = number_of_commits
    unless (last_git_commit[:message].include?("Bump build number to"))
      increment_build_number(
        build_number: build_number,
      )
      begin
        git_add
        ensure_git_status_clean
      rescue
        git_commit(path: "*", message: "Bump build number to #{build_number}")
      end
    end
  end

  desc "clear build and deriveData"
  lane :clear_all do
    clean_cocoapods_cache
    clean_build_artifacts
    clear_derived_data(derived_data_path: 'derivedData')
    sh "rm -rf #{ENV['PWD']}/derivedData/*"
    sh "rm -rf #{ENV['PWD']}/build/*"
  end
end
