name: Create the Release pull request

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release_pull_request:
    if: ${{ github.event.inputs.jobToRun == 'release' || github.event.inputs.jobToRun == 'all' }}
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get release version
        run: |
          filename=$(find . -maxdepth 1 -name "*.xcodeproj" -exec basename {} .xcodeproj \; | head -n 1)
          release_version=$(sed -n 's/.*MARKETING_VERSION *= *\([^;]*\);.*/\1/p' "$filename.xcodeproj/project.pbxproj" | head -n 1 | sed 's/^[^=]*=\s*//' | tr -d ' ')
          echo $release_version
          echo "RELEASE_VERSION=$release_version" >> "$GITHUB_ENV"

      - uses: nimblehq/github-actions-workflows/create_release_pull_request@0.1.10
        with:
          release_version: ${{ env.RELEASE_VERSION }}
          changelog_configuration: ".github/workflows/configs/changelog-config.json"
          assignee: bot-nimble