name: Test Install Script

on:
  push:
    branches: [ feature/**, bug/**, chore/** ]

jobs:
  Test:
    name: Test
    runs-on: macOS-12
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Bundle install
      run: bundle install

    - name: Start Install Script for Template App
      run: sh make.sh --bundle-id co.nimblehq.template --bundle-id-staging co.nimblehq.template.staging --project-name TemplateApp

    - name: Build and Test
      run: bundle exec fastlane build_and_test
      env:
        CI: true
