name: Test UIKit Install Script

on:
  push:
    branches: [ feature/**, bug/**, chore/** ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    name: Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Bundle install
      run: bundle install

    - name: Start Install Script for UIKit Template App
      run: swift run --package-path Scripts/Swift/iOSTemplateMaker iOSTemplateMaker make --bundle-id-production co.nimblehq.ios.templates --bundle-id-staging co.nimblehq.ios.templates.staging --bundle-id-dev co.nimblehq.ios.templates.dev --project-name TemplateApp --interface UIKit

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true
