name: Test Upload Build to Firebase

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS
### FIREBASE_TOKEN
### STAGING_FIREBASE_APP_ID
### TEAM_ID

on:
  pull_request
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Determine Runner Port
      id: runner_port
      run: |
        last_char=$(echo "${{ runner.name }}" | tail -c 2 | head -c 1)
        if [ "$last_char" = "1" ]; then
          echo "runner_port=2000" >> $GITHUB_ENV
          echo "test_device=iPhone 14 Pro Max" >> $GITHUB_ENV
        else
          echo "runner_port=2001" >> $GITHUB_ENV
          echo "test_device=iPhone SE (3rd generation)" >> $GITHUB_ENV
        fi
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Firebase-Tools
      run: |
        yarn global add firebase-tools
        echo "$(yarn global bin)" >> $GITHUB_PATH

    - name: Bundle install
      run: bundle install

    - name: Cache Pods
      uses: actions/cache@v3
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Start Install Script for Template App
      run: sh make.sh --bundle-id co.nimblehq.ios.templates --bundle-id-staging co.nimblehq.ios.templates.staging --project-name TemplateApp --interface UIKit

    - name: Start Setup Script for Template App Firebase Upload
      run: sh set_up_test_firebase.sh
      env:
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        STAGING_FIREBASE_APP_ID: ${{ secrets.STAGING_FIREBASE_APP_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}

    - name: Set Up Test Project for Firebase
      run: |
       bundle exec fastlane setUpTestProject --swift_server_port ${{ env.runner_port }}

    - name: Sync Ad Hoc Code Signing
      run: |
       bundle exec fastlane syncAdHocStagingCodeSigning --swift_server_port ${{ env.runner_port }}
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Build App and Distribute to Firebase
      run: |
       bundle exec fastlane buildStagingAndUploadToFirebase --swift_server_port ${{ env.runner_port }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('v{0}({1})-{2}', env.VERSION_NUMBER, env.BUILD_NUMBER, env.TAG_TYPE) }}
        path: |
          ${{ env.IPA_OUTPUT_PATH }}
          ${{ env.DSYM_OUTPUT_PATH }}
      env:
        TAG_TYPE: Staging_Firebase
